### REGRESSION MODEL SELECTION

In [82]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import r2_score

### IMPORTING THE DATASET

In [83]:
dataset = pd.read_csv('Data.csv')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [84]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [85]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [86]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### SPLIT THE DATASET

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

In [88]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [89]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


### MODELS

#### MULTIPLE LINEAR REGRESSION

In [90]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(r2_score(y_test, y_pred))

0.9325315554761303


#### POLYNOMIAL REGRESSION

In [93]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
X_poly_test = poly_reg.transform(X_test)
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y_train)
y_pred = lin_reg.predict(X_poly_test)
print(r2_score(y_test, y_pred))

0.9458193637378739


#### SVR

In [95]:
from sklearn.preprocessing import StandardScaler
y = y.reshape((len(y),1))
sc_x = StandardScaler()
X = sc_x.fit_transform(X)
sc_y = StandardScaler()
y = sc_y.fit_transform(y)

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

In [97]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)
print(r2_score(y_test, y_pred))

c:\Users\Gabriel\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9480757674401596


#### DECISION TREE REGRESSION

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

In [99]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)
print(r2_score(y_test, y_pred))

0.9245764487043432


#### RANDOM FOREST REGRESSION

In [100]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10)
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)
print(r2_score(y_test, y_pred))

0.9605791621959762


C:\Users\Gabriel\AppData\Local\Temp\ipykernel_17248\219810825.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train,y_train)
